### PR TITLE
fix(luasnip): correctly remove duplicate snippets

### LINKED ISSUE #5210: every snippet has it's duplicate for some reason.
### Discussed in https://github.com/LazyVim/LazyVim/discussions/5142

<div type='discussions-op-text'>

<sup>Originally posted by **milkpuff** December 17, 2024</sup>
 I enable lazyextra `coding.blink` and `coding.luasnip`:
图片
If disable `coding.luasnip`, snippets show once, but some snippet like `classi` raise error:
`/usr/share/nvim/runtime/lua/vim/lsp/_snippet_grammar.lua:177: snippet parsing failed`</div>

I also have this issue. I use luasnip with pretty basic setup.
here is [my LazyVim config](https://github.com/monoira/.dotfiles/tree/main/nvim/.config/nvim)

Image

### PR DESCRIPTION
**Pull request by dpetka2001**
## Description
Remove `snippets` from `opts.sources.default` when Luasnip is enabled to not get duplicate snippets.

## Related Issue(s)
Fixes #5210

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

File: lua/lazyvim/plugins/extras/coding/luasnip.lua [hunk 1]
```diff
@@ -85,4 +84,12 @@ return {
       },
     },
   },
+
+  -- Luasnip sources for blink
+  {
+    "saghen/blink.cmp",
+    opts = function(_, opts)
+      opts.sources.default = { "lsp", "path", "luasnip", "buffer" }
```
Comment (folke) [inline lua/lazyvim/plugins/extras/coding/luasnip.lua:92]: this will remove lazydev and possibly AI providers.
Better to just append luasnip and `vim.tbl_filter` snippets out?

Comment (dpetka2001) [reply lua/lazyvim/plugins/extras/coding/luasnip.lua]: Tnx didn't think about that. `vim.tbl_filter` does indeed make more sense. Tnx for your suggestion :smile:

**Comment by folke** [comment]
ty!
