### PR TITLE
fix(statuscolumn): `%r` deprecated in nightly and `%l` handles everything

### LINKED ISSUE #3721: bug: relative number not working
### Did you check docs and existing issues?

- [X] I have read all the LazyVim docs
- [X] I have searched the existing issues of LazyVim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.11.0-dev-274+g1a1c76604-Homebrew

### Operating system/version

MacOS 14.5

### Describe the bug

image

By pressing SPACE-uL, it only shows current line number while the "relative numbers" can't be seen anywhere. It used to work fine but don't know somehow it ends up like this.  

### Steps To Reproduce

SPACE-uL

### Expected Behavior

shows relative numbers

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", import = "lazyvim.plugins" },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

### PR DESCRIPTION
**Pull request by dpetka2001**
## What is this PR for?

Fix correctly showing relative numbers in `statuscolumn` after recent breaking changes on [nightly](https://github.com/neovim/neovim/pull/29357).

Please feel free to disregard this PR if a better solution is possible.

## Does this PR fix an existing issue?
Fixes #3721 

## Checklist

- [x] I've read the [CONTRIBUTING](https://github.com/LazyVim/LazyVim/blob/main/CONTRIBUTING.md) guidelines.

### CODE REVIEW

File: lua/lazyvim/util/ui.lua [hunk 1]
```diff
@@ -141,9 +141,17 @@ function M.statuscolumn()
...
+        components[2] = is_num and "%l" or "%r" -- the current line
+      end
     else
-      components[2] = is_relnum and "%r" or "%l" -- other lines
+      if vim.fn.has("nvim-0.11") == 1 then
+        components[2] = "%l" -- other lines
+      else
+        components[2] = is_relnum and "%r" or "%l" -- other lines
+      end
     end
```
Comment (bryanniwa) [inline lua/lazyvim/util/ui.lua:155]: I feel like simplifying this to the following more clearly separates the behaviour of the new change
```lua
    if vim.fn.has("nvim-0.11") == 1 then
      components[2] = "%l" -- 0.11 handles both the current and other lines with %l
    else
      if vim.v.relnum == 0 then
        components[2] = is_num and "%l" or "%r" -- the current line
      else
        components[2] = is_relnum and "%r" or "%l" -- other lines
      end
    end
```

Comment (dpetka2001) [reply lua/lazyvim/util/ui.lua]: @bryanniwa Thank you very much for improving and simplifying the logic even more. 

Just pushed the new changes you suggested :smile:

**Comment by dpetka2001** [comment]
@bryanniwa I was hasty and made the changes directly in my branch and forced-pushed. I should have accepted the suggested changes by you, so you appeared as co-author as well. Sorry about that.

**Comment by bryanniwa** [comment]
> @bryanniwa I was hasty and made the changes directly in my branch and forced-pushed. I should have accepted the suggested changes by you, so you appeared as co-author as well. Sorry about that.

No problem! Happy to help regardless

**Comment by folke** [comment]
Thanks!

**Comment by iamxiaojianzheng** [comment]
@dpetka2001 

I updated this change, but I lost the display of the relative line number.

My nvim version is NVIM v0.11.0-dev-250+g61aabe073
